-- SaleSmart AI production RLS policies
-- Run this in Supabase SQL Editor after confirming your tables exist.
-- Tables expected: orders, credits, usage_logs.

create table if not exists orders (
  id bigint generated by default as identity primary key,
  email text,
  plan text,
  amount numeric,
  credits integer,
  status text,
  razorpay_payment_id text,
  razorpay_order_id text,
  created_at timestamptz default now()
);

create table if not exists credits (
  id bigint generated by default as identity primary key,
  email text unique,
  balance integer default 0,
  updated_at timestamptz default now()
);

create table if not exists usage_logs (
  id bigint generated by default as identity primary key,
  email text,
  tool text,
  cost integer,
  balance_after integer,
  created_at timestamptz default now()
);

alter table orders     enable row level security;
alter table credits    enable row level security;
alter table usage_logs enable row level security;

-- Drop all old policies before recreating
drop policy if exists "Users can read their own orders"       on orders;
drop policy if exists "Users can insert their own orders"     on orders;
drop policy if exists "Users can read their own credits"      on credits;
drop policy if exists "Users can upsert their own credits"    on credits;
drop policy if exists "Users can update their own credits"    on credits;
drop policy if exists "Users can read their own usage logs"   on usage_logs;
drop policy if exists "Users can insert their own usage logs" on usage_logs;

-- orders: read-only for users; all writes go through server API (service role key)
create policy "Users can read their own orders"
on orders for select
using (email = auth.jwt() ->> 'email');

-- credits: read-only for users; all writes go through server API (service role key)
create policy "Users can read their own credits"
on credits for select
using (email = auth.jwt() ->> 'email');

-- usage_logs: read-only for users; inserts happen server-side in gemini.js
create policy "Users can read their own usage logs"
on usage_logs for select
using (email = auth.jwt() ->> 'email');

-- NOTE: INSERT and UPDATE on credits, orders, and usage_logs are intentionally
-- not granted to authenticated users. All writes go through the server API
-- routes using the SUPABASE_SERVICE_ROLE_KEY environment variable, which
-- bypasses RLS. This prevents any client-side credit manipulation.

-- Repair accounts that received a trial order but still show 0 credits.
-- This does not refill people who already have a positive balance.
insert into credits (email, balance, updated_at)
select
  trial.email,
  greatest(0, coalesce(trial.credits, 10) - coalesce(used.total_cost, 0)) as balance,
  now()
from (
  select email, max(credits) as credits
  from orders
  where status = 'trial' and email is not null
  group by email
) trial
left join (
  select email, sum(coalesce(cost, 0)) as total_cost
  from usage_logs
  where email is not null
  group by email
) used on used.email = trial.email
on conflict (email)
do update set
  balance = excluded.balance,
  updated_at = now()
where credits.balance = 0;
