-- SaleSmart AI production schema, RLS policies, and transactional RPCs.
-- Run in the Supabase SQL editor before deploying the matching API files.

create extension if not exists pgcrypto;

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  plan text,
  amount numeric,
  credits integer,
  status text,
  razorpay_payment_id text,
  razorpay_order_id text,
  created_at timestamptz not null default now()
);

create table if not exists credits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  email text unique,
  balance integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists usage_logs (
  id bigint generated by default as identity primary key,
  request_id uuid,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  tool text,
  cost integer,
  balance_after integer,
  created_at timestamptz not null default now()
);

-- Safe upgrades for installations created by an older version of this file.
alter table orders add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table credits add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table usage_logs add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table usage_logs add column if not exists request_id uuid;

update orders o
set user_id = u.id
from auth.users u
where o.user_id is null and lower(o.email) = lower(u.email);

update credits c
set user_id = u.id
from auth.users u
where c.user_id is null and lower(c.email) = lower(u.email);

update usage_logs l
set user_id = u.id
from auth.users u
where l.user_id is null and lower(l.email) = lower(u.email);

update credits set balance = 0 where balance < 0;

with ranked as (
  select
    id,
    user_id,
    row_number() over (partition by user_id order by updated_at desc, id desc) as row_number,
    sum(balance) over (partition by user_id) as merged_balance
  from credits
  where user_id is not null
),
keepers as (
  update credits c
  set balance = r.merged_balance, updated_at = now()
  from ranked r
  where c.id = r.id and r.row_number = 1
  returning c.user_id, c.id
)
delete from credits c
using ranked r
where c.id = r.id and r.row_number > 1;

create unique index if not exists credits_user_id_key on credits(user_id);
create index if not exists orders_user_created_idx on orders(user_id, created_at desc);
create index if not exists usage_logs_user_created_idx on usage_logs(user_id, created_at desc);
create unique index if not exists usage_logs_request_id_key
  on usage_logs(request_id) where request_id is not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'credits_balance_nonnegative' and conrelid = 'credits'::regclass
  ) then
    alter table credits add constraint credits_balance_nonnegative check (balance >= 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'orders_amount_nonnegative' and conrelid = 'orders'::regclass
  ) then
    alter table orders add constraint orders_amount_nonnegative check (amount >= 0) not valid;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'orders_credits_nonnegative' and conrelid = 'orders'::regclass
  ) then
    alter table orders add constraint orders_credits_nonnegative check (credits >= 0) not valid;
  end if;
end
$$;

create table if not exists payment_events (
  razorpay_payment_id text primary key,
  razorpay_order_id text not null unique,
  user_id uuid not null references auth.users(id) on delete restrict,
  email text not null,
  plan text not null,
  amount integer not null check (amount >= 0),
  credits integer not null check (credits > 0),
  created_at timestamptz not null default now()
);

create table if not exists trial_claims (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  claimed_at timestamptz not null default now()
);

create table if not exists credit_reservations (
  request_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  tool text not null,
  status text not null check (status in ('reserved', 'completed', 'refunded')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists api_rate_limits (
  subject_key text not null,
  route text not null,
  window_start timestamptz not null default now(),
  request_count integer not null default 0,
  primary key (subject_key, route)
);

-- Seed idempotency records for payments and trials handled before this upgrade.
insert into payment_events (
  razorpay_payment_id, razorpay_order_id, user_id, email, plan, amount, credits, created_at
)
select distinct on (razorpay_payment_id)
  razorpay_payment_id,
  razorpay_order_id,
  user_id,
  email,
  plan,
  greatest(0, coalesce(amount, 0)::integer),
  greatest(1, coalesce(credits, 1)),
  created_at
from orders
where status = 'paid'
  and user_id is not null
  and email is not null
  and plan is not null
  and razorpay_payment_id is not null
  and razorpay_order_id is not null
order by razorpay_payment_id, created_at asc
on conflict do nothing;

insert into trial_claims (user_id, email, claimed_at)
select distinct on (user_id) user_id, email, created_at
from orders
where status = 'trial' and user_id is not null and email is not null
order by user_id, created_at asc
on conflict (user_id) do nothing;

alter table orders enable row level security;
alter table credits enable row level security;
alter table usage_logs enable row level security;
alter table payment_events enable row level security;
alter table trial_claims enable row level security;
alter table credit_reservations enable row level security;
alter table api_rate_limits enable row level security;

drop policy if exists "Users can read their own orders" on orders;
drop policy if exists "Users can insert their own orders" on orders;
drop policy if exists "Users can read their own credits" on credits;
drop policy if exists "Users can upsert their own credits" on credits;
drop policy if exists "Users can update their own credits" on credits;
drop policy if exists "Users can read their own usage logs" on usage_logs;
drop policy if exists "Users can insert their own usage logs" on usage_logs;

create policy "Users can read their own orders"
on orders for select
using (user_id = auth.uid());

create policy "Users can read their own credits"
on credits for select
using (user_id = auth.uid());

create policy "Users can read their own usage logs"
on usage_logs for select
using (user_id = auth.uid());

create or replace function reserve_credit(
  p_request_id uuid,
  p_user_id uuid,
  p_email text,
  p_tool text
)
returns table(success boolean, balance integer, message text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer;
begin
  update credits
  set user_id = p_user_id, email = lower(p_email), updated_at = now()
  where user_id is null and lower(email) = lower(p_email);

  insert into credit_reservations(request_id, user_id, email, tool, status)
  values (p_request_id, p_user_id, lower(p_email), p_tool, 'reserved')
  on conflict (request_id) do nothing;

  if not found then
    select c.balance into v_balance from credits c where c.user_id = p_user_id;
    return query select false, coalesce(v_balance, 0), 'Duplicate generation request';
    return;
  end if;

  update credits
  set balance = credits.balance - 1, updated_at = now()
  where user_id = p_user_id and credits.balance > 0
  returning credits.balance into v_balance;

  if v_balance is null then
    delete from credit_reservations where request_id = p_request_id;
    select c.balance into v_balance from credits c where c.user_id = p_user_id;
    return query select false, coalesce(v_balance, 0), 'No credits remaining';
    return;
  end if;

  return query select true, v_balance, 'Credit reserved';
end;
$$;

create or replace function complete_credit_use(p_request_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation credit_reservations%rowtype;
  v_balance integer;
begin
  update credit_reservations
  set status = 'completed', updated_at = now()
  where request_id = p_request_id and status = 'reserved'
  returning * into v_reservation;

  if v_reservation.request_id is null then
    return false;
  end if;

  select balance into v_balance from credits where user_id = v_reservation.user_id;

  insert into usage_logs(request_id, user_id, email, tool, cost, balance_after)
  values (
    p_request_id, v_reservation.user_id, v_reservation.email,
    v_reservation.tool, 1, coalesce(v_balance, 0)
  );
  return true;
end;
$$;

create or replace function refund_credit(p_request_id uuid)
returns table(refunded boolean, balance integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_balance integer;
begin
  update credit_reservations
  set status = 'refunded', updated_at = now()
  where request_id = p_request_id and status = 'reserved'
  returning user_id into v_user_id;

  if v_user_id is null then
    select c.balance into v_balance
    from credits c
    join credit_reservations r on r.user_id = c.user_id
    where r.request_id = p_request_id;
    return query select false, coalesce(v_balance, 0);
    return;
  end if;

  update credits
  set balance = credits.balance + 1, updated_at = now()
  where user_id = v_user_id
  returning credits.balance into v_balance;

  return query select true, coalesce(v_balance, 0);
end;
$$;

create or replace function grant_trial_atomic(
  p_user_id uuid,
  p_email text,
  p_credits integer default 10
)
returns table(granted boolean, balance integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_claimed uuid;
  v_balance integer;
begin
  update credits
  set user_id = p_user_id, email = lower(p_email), updated_at = now()
  where user_id is null and lower(email) = lower(p_email);

  insert into trial_claims(user_id, email)
  values (p_user_id, lower(p_email))
  on conflict (user_id) do nothing
  returning user_id into v_claimed;

  if v_claimed is null then
    select c.balance into v_balance from credits c where c.user_id = p_user_id;
    return query select false, coalesce(v_balance, 0);
    return;
  end if;

  insert into credits(user_id, email, balance, updated_at)
  values (p_user_id, lower(p_email), p_credits, now())
  on conflict (user_id) do update
  set balance = credits.balance + excluded.balance,
      email = excluded.email,
      updated_at = now()
  returning credits.balance into v_balance;

  insert into orders(user_id, email, plan, amount, credits, status)
  values (p_user_id, lower(p_email), 'trial', 0, p_credits, 'trial');

  return query select true, v_balance;
end;
$$;

create or replace function finalize_payment_atomic(
  p_user_id uuid,
  p_email text,
  p_plan text,
  p_amount integer,
  p_credits integer,
  p_payment_id text,
  p_order_id text
)
returns table(processed boolean, balance integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inserted text;
  v_balance integer;
begin
  update credits
  set user_id = p_user_id, email = lower(p_email), updated_at = now()
  where user_id is null and lower(email) = lower(p_email);

  insert into payment_events(
    razorpay_payment_id, razorpay_order_id, user_id, email, plan, amount, credits
  )
  values (
    p_payment_id, p_order_id, p_user_id, lower(p_email), p_plan, p_amount, p_credits
  )
  on conflict do nothing
  returning razorpay_payment_id into v_inserted;

  if v_inserted is null then
    select c.balance into v_balance from credits c where c.user_id = p_user_id;
    return query select false, coalesce(v_balance, 0);
    return;
  end if;

  insert into credits(user_id, email, balance, updated_at)
  values (p_user_id, lower(p_email), p_credits, now())
  on conflict (user_id) do update
  set balance = credits.balance + excluded.balance,
      email = excluded.email,
      updated_at = now()
  returning credits.balance into v_balance;

  insert into orders(
    user_id, email, plan, amount, credits, status,
    razorpay_payment_id, razorpay_order_id
  )
  values (
    p_user_id, lower(p_email), p_plan, p_amount, p_credits, 'paid',
    p_payment_id, p_order_id
  );

  return query select true, v_balance;
end;
$$;

create or replace function check_rate_limit(
  p_subject_key text,
  p_route text,
  p_limit integer,
  p_window_seconds integer
)
returns table(allowed boolean, retry_after integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_window_start timestamptz;
  v_now timestamptz := now();
begin
  insert into api_rate_limits(subject_key, route, window_start, request_count)
  values (p_subject_key, p_route, v_now, 1)
  on conflict (subject_key, route) do update
  set window_start = case
        when api_rate_limits.window_start <= v_now - make_interval(secs => p_window_seconds)
        then v_now else api_rate_limits.window_start end,
      request_count = case
        when api_rate_limits.window_start <= v_now - make_interval(secs => p_window_seconds)
        then 1 else api_rate_limits.request_count + 1 end
  returning request_count, window_start into v_count, v_window_start;

  return query
  select
    v_count <= greatest(1, p_limit),
    case when v_count <= greatest(1, p_limit) then 0
      else greatest(1, ceil(extract(epoch from (
        v_window_start + make_interval(secs => p_window_seconds) - v_now
      )))::integer)
    end;
end;
$$;

create or replace function admin_dashboard_summary()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'totals', jsonb_build_object(
      'users', (select count(*) from credits),
      'credits', (select coalesce(sum(balance), 0) from credits),
      'orders', (select count(*) from orders),
      'revenue', (select coalesce(sum(amount), 0) from orders where status = 'paid')
    ),
    'orders', coalesce((
      select jsonb_agg(to_jsonb(recent_orders) order by created_at desc)
      from (
        select email, plan, amount, credits, status, created_at
        from orders
        order by created_at desc
        limit 50
      ) recent_orders
    ), '[]'::jsonb)
  );
$$;

revoke all on function reserve_credit(uuid, uuid, text, text) from public, anon, authenticated;
revoke all on function complete_credit_use(uuid) from public, anon, authenticated;
revoke all on function refund_credit(uuid) from public, anon, authenticated;
revoke all on function grant_trial_atomic(uuid, text, integer) from public, anon, authenticated;
revoke all on function finalize_payment_atomic(uuid, text, text, integer, integer, text, text) from public, anon, authenticated;
revoke all on function check_rate_limit(text, text, integer, integer) from public, anon, authenticated;
revoke all on function admin_dashboard_summary() from public, anon, authenticated;

grant execute on function reserve_credit(uuid, uuid, text, text) to service_role;
grant execute on function complete_credit_use(uuid) to service_role;
grant execute on function refund_credit(uuid) to service_role;
grant execute on function grant_trial_atomic(uuid, text, integer) to service_role;
grant execute on function finalize_payment_atomic(uuid, text, text, integer, integer, text, text) to service_role;
grant execute on function check_rate_limit(text, text, integer, integer) to service_role;
grant execute on function admin_dashboard_summary() to service_role;
